// license:BSD-3-Clause
// copyright-holders:mcwild77
//
// GENERATED by devnotes/tools/padmap-gen.py from input_layouts.json — do not edit.
// Author layouts in devnotes/tools/padmap.html, then re-run the generator.
//
// One row per port set: which RetroPad control produces each MAME button, and what every control is
// called in the frontend's Controls menu.  The label array is DERIVED from the button assignments
// rather than written beside them, which is why the two can no longer disagree — see the generator's
// docstring and devnotes/input-map.md §5.1 for the bug that made this necessary.
//
// Included from libretro_m2_input.cpp inside its anonymous namespace, after the SOURCE_* constants.

char const *const SETS_airwlkrs[] = { "airwlkrs", nullptr };
char const *const SETS_daytona[] = { "daytona", nullptr };
char const *const SETS_doa[] = { "doa", nullptr };
char const *const SETS_dynamcop[] = { "dynamcop", nullptr };
char const *const SETS_gunblade[] = { "gunblade", nullptr };
char const *const SETS_indy500[] = { "indy500", "stcc", nullptr };
char const *const SETS_manxtt[] = { "manxtt", nullptr };
char const *const SETS_model2crx[] = { "rascot2", nullptr };
char const *const SETS_motoraid[] = { "motoraid", nullptr };
char const *const SETS_overrev[] = { "overrev", nullptr };
char const *const SETS_pltkids[] = { "pltkids", nullptr };
char const *const SETS_rchase2[] = { "rchase2", nullptr };
char const *const SETS_rchase2a[] = { "rchase2a", nullptr };
char const *const SETS_schamp[] = { "schamp", nullptr };
char const *const SETS_sgt24h[] = { "sgt24h", nullptr };
char const *const SETS_skisuprg[] = { "skisuprg", nullptr };
char const *const SETS_srallyc[] = { "srallyc", nullptr };
char const *const SETS_vcop[] = { "vcop", nullptr };
char const *const SETS_vcop2[] = { "vcop2", nullptr };
char const *const SETS_vf2[] = { "vf2", "hpyagu98", "fvipers", "lastbrnx", nullptr };
char const *const SETS_vstriker[] = { "vstriker", nullptr };
char const *const SETS_zerogun[] = { "zerogun", nullptr };

// The fallback, and it is deliberately identical to the layout every set used before there were
// per-game rows: the regression check for this whole change is that a set with no row of its own is
// byte-identical to today, and that only holds if this stays exactly what BUTTON_LAYOUTS' Classic row
// was. Do not "improve" it.
// the fallback for every port set with no row — today's Classic layout, unchanged
constexpr game_layout GENERIC_LAYOUT =
{
	"generic",
	nullptr,
	false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
	{
		RETRO_DEVICE_ID_JOYPAD_B,
		RETRO_DEVICE_ID_JOYPAD_A,
		RETRO_DEVICE_ID_JOYPAD_Y,
		RETRO_DEVICE_ID_JOYPAD_X,
		RETRO_DEVICE_ID_JOYPAD_R,
		RETRO_DEVICE_ID_JOYPAD_L,
		SOURCE_L2_AXIS,
		SOURCE_R2_AXIS,
		RETRO_DEVICE_ID_JOYPAD_R3,
	},
	{
		/*  0 B        BUTTON1 */ "Button 1",
		/*  1 Y        BUTTON3 */ "Button 3",
		/*  2 SELECT           */ "Coin",
		/*  3 START            */ "Start",
		/*  4 UP               */ "Up",
		/*  5 DOWN             */ "Down",
		/*  6 LEFT             */ "Left",
		/*  7 RIGHT            */ "Right",
		/*  8 A        BUTTON2 */ "Button 2",
		/*  9 X        BUTTON4 */ "Button 4",
		/* 10 L        BUTTON6 */ "Button 6",
		/* 11 R        BUTTON5 */ "Button 5",
		/* 12 L2       BUTTON7 */ "Brake / Button 7",
		/* 13 R2       BUTTON8 */ "Accelerator / Button 8",
		/* 14 L3               */ "Service Coin",
		/* 15 R3       BUTTON9 */ "Button 9",
		/* 16 LSTICK_X         */ "Steering / Stick X",
		/* 17 LSTICK_Y         */ "Stick Y",
		/* 18 RSTICK_X         */ "Right Stick X",
		/* 19 RSTICK_Y         */ "Right Stick Y",
	},
};

constexpr game_layout GAME_LAYOUTS[] = {
	// verified: NOT YET MEASURED IN GAME
	{
		"airwlkrs",
		SETS_airwlkrs,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Button 1 */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Button 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Button 3 */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 Button 4 */
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON5 Button 5 */
			RETRO_DEVICE_ID_JOYPAD_L,  /* BUTTON6 Button 6 */
			SOURCE_L2_AXIS,  /* BUTTON7 Button 7 */
			SOURCE_R2_AXIS,  /* BUTTON8 Button 8 */
			RETRO_DEVICE_ID_JOYPAD_R3,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Button 1",
			/*  1 Y        BUTTON3 */ "Button 3",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON2 */ "Button 2",
			/*  9 X        BUTTON4 */ "Button 4",
			/* 10 L        BUTTON6 */ "Button 6",
			/* 11 R        BUTTON5 */ "Button 5",
			/* 12 L2       BUTTON7 */ "Button 7",
			/* 13 R2       BUTTON8 */ "Button 8",
			/* 14 L3               */ "Service Coin",
			/* 15 R3       BUTTON9 */ "Button 9",
			/* 16 LSTICK_X         */ nullptr,
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// one-player cabinet: wheel, two pedals, a four-position gearbox and VR1-4 in a row. The d-pad assignment is
	// clockwise from Up and is the one arbitrary choice: the cabinet has VR1-4 left-to-right and a d-pad is not a
	// row.
	// verified: NOT YET MEASURED IN GAME
	{
		"daytona",
		SETS_daytona,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			SOURCE_NONE,  /* BUTTON1 GEAR N — GEAR N: the pad is out of buttons, and neutral is reachable by shifting down out of gear 1 */
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON2 GEAR 1 */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON3 GEAR 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON4 GEAR 3 */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON5 GEAR 4 */
			RETRO_DEVICE_ID_JOYPAD_UP,  /* BUTTON6 VR1 (Red) */
			RETRO_DEVICE_ID_JOYPAD_RIGHT,  /* BUTTON7 VR2 (Blue) */
			RETRO_DEVICE_ID_JOYPAD_DOWN,  /* BUTTON8 VR3 (Yellow) */
			RETRO_DEVICE_ID_JOYPAD_LEFT,  /* BUTTON9 VR4 (Green) */
		},
		{
			/*  0 B        BUTTON2 */ "GEAR 1",
			/*  1 Y        BUTTON4 */ "GEAR 3",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP       BUTTON6 */ "VR1 (Red)",
			/*  5 DOWN     BUTTON8 */ "VR3 (Yellow)",
			/*  6 LEFT     BUTTON9 */ "VR4 (Green)",
			/*  7 RIGHT    BUTTON7 */ "VR2 (Blue)",
			/*  8 A        BUTTON3 */ "GEAR 2",
			/*  9 X        BUTTON5 */ "GEAR 4",
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ "Brake",
			/* 13 R2               */ "Accelerator",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// three buttons: Hold / Punch / Kick
	// verified: NOT YET MEASURED IN GAME
	{
		"doa",
		SETS_doa,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON1 Hold */
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON2 Punch */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON3 Kick */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON2 */ "Punch",
			/*  1 Y        BUTTON1 */ "Hold",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Up",
			/*  5 DOWN             */ "Down",
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A        BUTTON3 */ "Kick",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"dynamcop",
		SETS_dynamcop,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON1 Punch */
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON2 Kick */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON3 Jump */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON2 */ "Kick",
			/*  1 Y        BUTTON1 */ "Punch",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Up",
			/*  5 DOWN             */ "Down",
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A        BUTTON3 */ "Jump",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// as rchase2 with a different PORT_MINMAX
	// verified: NOT YET MEASURED IN GAME
	{
		"gunblade",
		SETS_gunblade,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Button 1 */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Button 1",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Stick X",
			/* 17 LSTICK_Y         */ "Stick Y",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"indy500",
		SETS_indy500,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON1 Shift Up */
			RETRO_DEVICE_ID_JOYPAD_L,  /* BUTTON2 Shift Down */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 View 1 (Zoom In) */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 View 2 (Zoom Out) */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y        BUTTON3 */ "View 1 (Zoom In)",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X        BUTTON4 */ "View 2 (Zoom Out)",
			/* 10 L        BUTTON2 */ "Shift Down",
			/* 11 R        BUTTON1 */ "Shift Up",
			/* 12 L2               */ "Brake Pedal",
			/* 13 R2               */ "Gas Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering Wheel",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"manxtt",
		SETS_manxtt,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON1 Shift Up */
			RETRO_DEVICE_ID_JOYPAD_L,  /* BUTTON2 Shift Down */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L        BUTTON2 */ "Shift Down",
			/* 11 R        BUTTON1 */ "Shift Up",
			/* 12 L2               */ "Brake",
			/* 13 R2               */ "Accelerator",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"model2crx",
		SETS_model2crx,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Button 1 */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Button 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Button 3 */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 Button 4 */
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON5 Button 5 */
			RETRO_DEVICE_ID_JOYPAD_L,  /* BUTTON6 Button 6 */
			SOURCE_L2_AXIS,  /* BUTTON7 Button 7 */
			SOURCE_R2_AXIS,  /* BUTTON8 Button 8 */
			RETRO_DEVICE_ID_JOYPAD_R3,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Button 1",
			/*  1 Y        BUTTON3 */ "Button 3",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON2 */ "Button 2",
			/*  9 X        BUTTON4 */ "Button 4",
			/* 10 L        BUTTON6 */ "Button 6",
			/* 11 R        BUTTON5 */ "Button 5",
			/* 12 L2       BUTTON7 */ "Button 7",
			/* 13 R2       BUTTON8 */ "Button 8",
			/* 14 L3               */ "Service Coin",
			/* 15 R3       BUTTON9 */ "Button 9",
			/* 16 LSTICK_X         */ nullptr,
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// bike cabinet: lean on the left stick, throttle and brake on the triggers, two buttons
	// verified: NOT YET MEASURED IN GAME
	{
		"motoraid",
		SETS_motoraid,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Punch */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Kick */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Punch",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON2 */ "Kick",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ "Brake",
			/* 13 R2               */ "Accelerator",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"overrev",
		SETS_overrev,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON1 Shift Up */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Shift Down */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 View 1 */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 View 2 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y        BUTTON3 */ "View 1",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON2 */ "Shift Down",
			/*  9 X        BUTTON4 */ "View 2",
			/* 10 L                */ nullptr,
			/* 11 R        BUTTON1 */ "Shift Up",
			/* 12 L2               */ "Brake Pedal",
			/* 13 R2               */ "Gas Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering Wheel",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// two buttons only
	// verified: NOT YET MEASURED IN GAME
	{
		"pltkids",
		SETS_pltkids,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Button 1 */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Button 1",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Up",
			/*  5 DOWN             */ "Down",
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A        BUTTON2 */ "Button 2",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// aim per player on that player's own left stick, one trigger each
	// verified: NOT YET MEASURED IN GAME
	{
		"rchase2",
		SETS_rchase2,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Button 1 */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Button 1",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Stick X",
			/* 17 LSTICK_Y         */ "Stick Y",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// as rchase2 with a wider range and no reverse; no ROMs locally, so the row is unmeasured
	// verified: NOT YET MEASURED IN GAME
	{
		"rchase2a",
		SETS_rchase2a,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Button 1 */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Button 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Button 3 */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 Button 4 */
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON5 Button 5 */
			RETRO_DEVICE_ID_JOYPAD_L,  /* BUTTON6 Button 6 */
			SOURCE_L2_AXIS,  /* BUTTON7 Button 7 */
			SOURCE_R2_AXIS,  /* BUTTON8 Button 8 */
			RETRO_DEVICE_ID_JOYPAD_R3,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Button 1",
			/*  1 Y        BUTTON3 */ "Button 3",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON2 */ "Button 2",
			/*  9 X        BUTTON4 */ "Button 4",
			/* 10 L        BUTTON6 */ "Button 6",
			/* 11 R        BUTTON5 */ "Button 5",
			/* 12 L2       BUTTON7 */ "Button 7",
			/* 13 R2       BUTTON8 */ "Button 8",
			/* 14 L3               */ "Service Coin",
			/* 15 R3       BUTTON9 */ "Button 9",
			/* 16 LSTICK_X         */ nullptr,
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"schamp",
		SETS_schamp,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Punch */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Kick */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Barrier */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Punch",
			/*  1 Y        BUTTON3 */ "Barrier",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Up",
			/*  5 DOWN             */ "Down",
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A        BUTTON2 */ "Kick",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"sgt24h",
		SETS_sgt24h,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON1 Shift Up */
			RETRO_DEVICE_ID_JOYPAD_L,  /* BUTTON2 Shift Down */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 View 1 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y        BUTTON3 */ "View 1",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L        BUTTON2 */ "Shift Down",
			/* 11 R        BUTTON1 */ "Shift Up",
			/* 12 L2               */ "Brake Pedal",
			/* 13 R2               */ "Gas Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering Wheel",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"skisuprg",
		SETS_skisuprg,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Select 1 */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Select 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Select 3 */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 Zoom Out */
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON5 Zoom In */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Select 1",
			/*  1 Y        BUTTON3 */ "Select 3",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Up",
			/*  5 DOWN             */ "Down",
			/*  6 LEFT             */ "Foot Sensor (L)",
			/*  7 RIGHT            */ "Foot Sensor (R)",
			/*  8 A        BUTTON2 */ "Select 2",
			/*  9 X        BUTTON4 */ "Zoom Out",
			/* 10 L                */ nullptr,
			/* 11 R        BUTTON5 */ "Zoom In",
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move / Inclining",
			/* 17 LSTICK_Y         */ "Move / Swing",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"srallyc",
		SETS_srallyc,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON1 GEAR N */
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON2 GEAR 1 */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON3 GEAR 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON4 GEAR 3 */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON5 GEAR 4 */
			RETRO_DEVICE_ID_JOYPAD_L,  /* BUTTON6 VR */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON2 */ "GEAR 1",
			/*  1 Y        BUTTON4 */ "GEAR 3",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON3 */ "GEAR 2",
			/*  9 X        BUTTON5 */ "GEAR 4",
			/* 10 L        BUTTON6 */ "VR",
			/* 11 R        BUTTON1 */ "Hand Brake / GEAR N",
			/* 12 L2               */ "Brake Pedal",
			/* 13 R2               */ "Accelerate Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering Wheel",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// lightgun cabinet; on a port left as a pad the trigger is button 1 and aim is the left stick
	// verified: NOT YET MEASURED IN GAME
	{
		"vcop",
		SETS_vcop,
		true,
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Trigger */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Trigger",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Aim X",
			/* 17 LSTICK_Y         */ "Aim Y",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// lightgun cabinet, same shape as vcop
	// verified: NOT YET MEASURED IN GAME
	{
		"vcop2",
		SETS_vcop2,
		true,
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Trigger */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Trigger",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Aim X",
			/* 17 LSTICK_Y         */ "Aim Y",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// three-button fighter on a four-way stick; shared by fvipers, lastbrnx and hpyagu98
	// verified: NOT YET MEASURED IN GAME
	{
		"vf2",
		SETS_vf2,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Punch */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Kick */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Guard */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Punch",
			/*  1 Y        BUTTON3 */ "Guard",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Up",
			/*  5 DOWN             */ "Down",
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A        BUTTON2 */ "Kick",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// three buttons. The driver's bit order is not its button order; these are by button number
	// verified: NOT YET MEASURED IN GAME
	{
		"vstriker",
		SETS_vstriker,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Short Pass */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Long Pass */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Shoot */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Short Pass",
			/*  1 Y        BUTTON3 */ "Shoot",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Up",
			/*  5 DOWN             */ "Down",
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A        BUTTON2 */ "Long Pass",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// two buttons only
	// verified: NOT YET MEASURED IN GAME
	{
		"zerogun",
		SETS_zerogun,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Button 1 */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Button 1",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Up",
			/*  5 DOWN             */ "Down",
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A        BUTTON2 */ "Button 2",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	}
};

static_assert(std::size(GAME_LAYOUTS) == 22, "regenerate input_layouts.ipp");
