// license:BSD-3-Clause
// copyright-holders:mcwild77
//
// GENERATED by devnotes/tools/padmap-gen.py from input_layouts.json — do not edit.
// Author layouts in devnotes/tools/padmap.html, then re-run the generator.
//
// One row per port set: which RetroPad control produces each MAME button, and what every control is
// called in the frontend's Controls menu.  The label array is DERIVED from the button assignments
// rather than written beside them, which is why the two can no longer disagree — see the generator's
// docstring and devnotes/input-map.md §5.1 for the bug that made this necessary.
//
// Included from libretro_m2_input.cpp inside its anonymous namespace, after the SOURCE_* constants.

char const *const SETS_acedrive[] = { "acedrive", nullptr };
char const *const SETS_adillor[] = { "adillor", nullptr };
char const *const SETS_airco22[] = { "airco22b", nullptr };
char const *const SETS_airwlkrs[] = { "airwlkrs", nullptr };
char const *const SETS_alpiner[] = { "alpinerd", "alpinr2b", nullptr };
char const *const SETS_alpines[] = { "alpines", nullptr };
char const *const SETS_aquajet[] = { "aquajet", nullptr };
char const *const SETS_cybrcomm[] = { "cybrcomm", nullptr };
char const *const SETS_cybrcycc[] = { "cybrcycc", nullptr };
char const *const SETS_cybsled[] = { "cybsled", nullptr };
char const *const SETS_daytona[] = { "daytona", nullptr };
char const *const SETS_desert[] = { "desert", nullptr };
char const *const SETS_dirtdash[] = { "dirtdash", nullptr };
char const *const SETS_doa[] = { "doa", nullptr };
char const *const SETS_dynamcop[] = { "dynamcop", nullptr };
char const *const SETS_gunblade[] = { "gunblade", nullptr };
char const *const SETS_indy500[] = { "indy500", "stcc", nullptr };
char const *const SETS_manxtt[] = { "manxtt", nullptr };
char const *const SETS_model2crx[] = { "rascot2", nullptr };
char const *const SETS_motoraid[] = { "motoraid", nullptr };
char const *const SETS_overrev[] = { "overrev", nullptr };
char const *const SETS_pltkids[] = { "pltkids", nullptr };
char const *const SETS_propcycl[] = { "propcycl", nullptr };
char const *const SETS_raverace[] = { "raverace", nullptr };
char const *const SETS_rchase2[] = { "rchase2", nullptr };
char const *const SETS_rchase2a[] = { "rchase2a", nullptr };
char const *const SETS_ridgera[] = { "ridgerac", "ridgerac3m", nullptr };
char const *const SETS_ridgera2[] = { "ridgera2", nullptr };
char const *const SETS_ridgeracf[] = { "ridgeracf", nullptr };
char const *const SETS_schamp[] = { "schamp", nullptr };
char const *const SETS_sgt24h[] = { "sgt24h", nullptr };
char const *const SETS_skisuprg[] = { "skisuprg", nullptr };
char const *const SETS_srallyc[] = { "srallyc", nullptr };
char const *const SETS_starblad[] = { "starblad", nullptr };
char const *const SETS_timecris[] = { "timecris", nullptr };
char const *const SETS_tokyowar[] = { "tokyowar", nullptr };
char const *const SETS_vcop[] = { "vcop", nullptr };
char const *const SETS_vcop2[] = { "vcop2", nullptr };
char const *const SETS_vf2[] = { "vf2", "hpyagu98", "fvipers", "lastbrnx", nullptr };
char const *const SETS_victlap[] = { "victlap", nullptr };
char const *const SETS_vstriker[] = { "vstriker", nullptr };
char const *const SETS_winrun[] = { "winrun", "winrungp", nullptr };
char const *const SETS_zerogun[] = { "zerogun", nullptr };

// The fallback, and it is deliberately identical to the layout every set used before there were
// per-game rows: the regression check for this whole change is that a set with no row of its own is
// byte-identical to today, and that only holds if this stays exactly what BUTTON_LAYOUTS' Classic row
// was. Do not "improve" it.
// the fallback for every port set with no row — today's Classic layout, unchanged
constexpr game_layout GENERIC_LAYOUT =
{
	"generic",
	nullptr,
	false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
	false,  // not a single-pad twin-stick cabinet
	{
		RETRO_DEVICE_ID_JOYPAD_B,
		RETRO_DEVICE_ID_JOYPAD_A,
		RETRO_DEVICE_ID_JOYPAD_Y,
		RETRO_DEVICE_ID_JOYPAD_X,
		RETRO_DEVICE_ID_JOYPAD_R,
		RETRO_DEVICE_ID_JOYPAD_L,
		SOURCE_L2_AXIS,
		SOURCE_R2_AXIS,
		RETRO_DEVICE_ID_JOYPAD_R3,
	},
	{
		/*  0 B        BUTTON1 */ "Button 1",
		/*  1 Y        BUTTON3 */ "Button 3",
		/*  2 SELECT           */ "Coin",
		/*  3 START            */ "Start",
		/*  4 UP               */ "Up",
		/*  5 DOWN             */ "Down",
		/*  6 LEFT             */ "Left",
		/*  7 RIGHT            */ "Right",
		/*  8 A        BUTTON2 */ "Button 2",
		/*  9 X        BUTTON4 */ "Button 4",
		/* 10 L        BUTTON6 */ "Button 6",
		/* 11 R        BUTTON5 */ "Button 5",
		/* 12 L2       BUTTON7 */ "Brake / Button 7",
		/* 13 R2       BUTTON8 */ "Accelerator / Button 8",
		/* 14 L3               */ "Service Coin",
		/* 15 R3       BUTTON9 */ "Button 9",
		/* 16 LSTICK_X         */ "Steering / Stick X",
		/* 17 LSTICK_Y         */ "Stick Y",
		/* 18 RSTICK_X         */ "Right Stick X",
		/* 19 RSTICK_Y         */ "Right Stick Y",
	},
};

constexpr game_layout GAME_LAYOUTS[] = {
	// verified: NOT YET MEASURED IN GAME
	{
		"acedrive",
		SETS_acedrive,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			SOURCE_NONE,  /* BUTTON1 Dev Service Enter */
			SOURCE_NONE,  /* BUTTON2 Dev Service Exit */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 View Change */
			SOURCE_NONE,  /* BUTTON4 Motion-Stop */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y        BUTTON3 */ "View Change",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Dev Service Up",
			/*  5 DOWN             */ "Dev Service Down",
			/*  6 LEFT             */ "Dev Service Left",
			/*  7 RIGHT            */ "Dev Service Right",
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ "Brake Pedal",
			/* 13 R2               */ "Gas Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move / Steering Wheel",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// Armadillo Racing — trackball cabinet; the two dev-service buttons are a CUSTOM port, not player controls.
	// verified: NOT YET MEASURED IN GAME
	{
		"adillor",
		SETS_adillor,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			SOURCE_NONE,  /* BUTTON1 Dev Service Enter */
			SOURCE_NONE,  /* BUTTON2 Dev Service Exit */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move / Trackball",
			/* 17 LSTICK_Y         */ "Move / Trackball",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// Air Combat 22 — flight stick + throttle; the throttle (AD_STICK_Z) defaults onto the right stick's X axis,
	// not a trigger.
	// verified: NOT YET MEASURED IN GAME
	{
		"airco22",
		SETS_airco22,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Gun Trigger */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Missile Button */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Gun Trigger",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON2 */ "Missile Button",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ "Throttle Stick",
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"airwlkrs",
		SETS_airwlkrs,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Button 1 */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Button 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Button 3 */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 Button 4 */
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON5 Button 5 */
			RETRO_DEVICE_ID_JOYPAD_L,  /* BUTTON6 Button 6 */
			SOURCE_L2_AXIS,  /* BUTTON7 Button 7 */
			SOURCE_R2_AXIS,  /* BUTTON8 Button 8 */
			RETRO_DEVICE_ID_JOYPAD_R3,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Button 1",
			/*  1 Y        BUTTON3 */ "Button 3",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON2 */ "Button 2",
			/*  9 X        BUTTON4 */ "Button 4",
			/* 10 L        BUTTON6 */ "Button 6",
			/* 11 R        BUTTON5 */ "Button 5",
			/* 12 L2       BUTTON7 */ "Button 7",
			/* 13 R2       BUTTON8 */ "Button 8",
			/* 14 L3               */ "Service Coin",
			/* 15 R3       BUTTON9 */ "Button 9",
			/* 16 LSTICK_X         */ nullptr,
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// Alpine Racer / Alpine Racer 2 — two independent leg-lean axes (Steps Swing / Steps Edge), tagged P1/P2 like
	// Cyber Sled's treads; reuses the single-pad twin-stick binding so the second leg lands on the right stick's X
	// axis. P1 Left/Right are unnamed digital fields on the same port.
	// verified: NOT YET MEASURED IN GAME
	{
		"alpiner",
		SETS_alpiner,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		true,  // single-pad twin-stick: OR pad 1 right stick onto player>1 IPT_AD_STICK
		{
			SOURCE_NONE,  /* BUTTON1 Button 1 */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steps Swing",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ "Steps Edge",
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// Alpine Surfer — same leg-lean pair as Alpine Racer.
	// verified: NOT YET MEASURED IN GAME
	{
		"alpines",
		SETS_alpines,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		true,  // single-pad twin-stick: OR pad 1 right stick onto player>1 IPT_AD_STICK
		{
			SOURCE_NONE,  /* BUTTON1 Button 1 */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steps Swing",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ "Steps Edge",
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// Aqua Jet — MAME gives no PORT_NAME for the paddle, pedal or AD_STICK_Y fields; labelled by best-guess
	// function pending a hand-check.
	// verified: NOT YET MEASURED IN GAME
	{
		"aquajet",
		SETS_aquajet,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			SOURCE_NONE,  /* BUTTON1 Button 1 */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ "Throttle",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering",
			/* 17 LSTICK_Y         */ "Lean",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// Cyber Commando — twin-stick mech cabinet, same shape as Cyber Sled (System 21); trigger/missile/view are
	// placed on both physical sticks so either hand fires.
	// verified: NOT YET MEASURED IN GAME
	{
		"cybrcomm",
		SETS_cybrcomm,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		true,  // single-pad twin-stick: OR pad 1 right stick onto player>1 IPT_AD_STICK
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Gun Trigger */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Missile Button */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 View Change */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Gun Trigger",
			/*  1 Y        BUTTON3 */ "View Change",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON2 */ "Missile Button",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move / Aim",
			/* 17 LSTICK_Y         */ "Move / Aim",
			/* 18 RSTICK_X         */ "Move / Aim",
			/* 19 RSTICK_Y         */ "Move / Aim",
		},
	},
	// Cyber Cycles — leaning-motorcycle cabinet; throttle grip and brake lever share the pedal axes.
	// verified: NOT YET MEASURED IN GAME
	{
		"cybrcycc",
		SETS_cybrcycc,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			SOURCE_NONE,  /* BUTTON1 Button 1 */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ "Brake Lever",
			/* 13 R2               */ "Throttle Grip",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering / Bike Bank",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// Cyber Sled — twin-stick tank; missile/gun/view on the face buttons, left stick aims.
	// verified: NOT YET MEASURED IN GAME
	{
		"cybsled",
		SETS_cybsled,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		true,  // single-pad twin-stick: OR pad 1 right stick onto player>1 IPT_AD_STICK
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Missile */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Gun */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Viewport Change */
			SOURCE_NONE,  /* BUTTON4 (unused) */
			SOURCE_NONE,  /* BUTTON5 (unused) */
			SOURCE_NONE,  /* BUTTON6 (unused) */
			SOURCE_NONE,  /* BUTTON7 (unused) */
			SOURCE_NONE,  /* BUTTON8 (unused) */
			SOURCE_NONE,  /* BUTTON9 (unused) */
		},
		{
			/*  0 B        BUTTON1 */ "Missile",
			/*  1 Y        BUTTON3 */ "Viewport Change",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON2 */ "Gun",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move / Aim",
			/* 17 LSTICK_Y         */ "Move / Aim",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// one-player cabinet: wheel, two pedals, a four-position gearbox and VR1-4 in a row. The d-pad assignment is
	// clockwise from Up and is the one arbitrary choice: the cabinet has VR1-4 left-to-right and a d-pad is not a
	// row.
	// verified: NOT YET MEASURED IN GAME
	{
		"daytona",
		SETS_daytona,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			SOURCE_NONE,  /* BUTTON1 GEAR N — GEAR N: the pad is out of buttons, and neutral is reachable by shifting down out of gear 1 */
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON2 GEAR 1 */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON3 GEAR 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON4 GEAR 3 */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON5 GEAR 4 */
			RETRO_DEVICE_ID_JOYPAD_UP,  /* BUTTON6 VR1 (Red) */
			RETRO_DEVICE_ID_JOYPAD_RIGHT,  /* BUTTON7 VR2 (Blue) */
			RETRO_DEVICE_ID_JOYPAD_DOWN,  /* BUTTON8 VR3 (Yellow) */
			RETRO_DEVICE_ID_JOYPAD_LEFT,  /* BUTTON9 VR4 (Green) */
		},
		{
			/*  0 B        BUTTON2 */ "GEAR 1",
			/*  1 Y        BUTTON4 */ "GEAR 3",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP       BUTTON6 */ "VR1 (Red)",
			/*  5 DOWN     BUTTON8 */ "VR3 (Yellow)",
			/*  6 LEFT     BUTTON9 */ "VR4 (Green)",
			/*  7 RIGHT    BUTTON7 */ "VR2 (Blue)",
			/*  8 A        BUTTON3 */ "GEAR 2",
			/*  9 X        BUTTON5 */ "GEAR 4",
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ "Brake",
			/* 13 R2               */ "Accelerator",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// tank cabinet: wheel, one pedal, six buttons. The buttons keep the generic row's order, so nothing a player
	// has learned moves and only the wording arrives. Two controls the generic row cannot describe: BRAKE is an
	// IPT_AD_STICK_Y, i.e. the left stick's Y axis and not a trigger, and there is no IPT_PEDAL2 at all, so L2
	// does nothing and is left unlabelled.
	// verified: NOT YET MEASURED IN GAME
	{
		"desert",
		SETS_desert,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Machine Gun */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Cannon */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Shift */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 VR1 (Blue) */
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON5 VR2 (Green) */
			RETRO_DEVICE_ID_JOYPAD_L,  /* BUTTON6 VR3 (Red) */
			SOURCE_NONE,  /* BUTTON7 Button 7 — the machine declares no IPT_BUTTON7 — leaving it on the L2 threshold, as the generic row does, binds a button that does not exist */
			SOURCE_NONE,  /* BUTTON8 Button 8 — no IPT_BUTTON8 either; the accelerator on R2 is IPT_PEDAL and is bound outside the layout */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Machine Gun",
			/*  1 Y        BUTTON3 */ "Shift",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON2 */ "Cannon",
			/*  9 X        BUTTON4 */ "VR1 (Blue)",
			/* 10 L        BUTTON6 */ "VR3 (Red)",
			/* 11 R        BUTTON5 */ "VR2 (Green)",
			/* 12 L2               */ nullptr,
			/* 13 R2               */ "Accelerator",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering",
			/* 17 LSTICK_Y         */ "Brake",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"dirtdash",
		SETS_dirtdash,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			SOURCE_NONE,  /* BUTTON1 Button 1 */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 View Change */
			SOURCE_NONE,  /* BUTTON4 Motion-Stop */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y        BUTTON3 */ "View Change",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Shift Down",
			/*  5 DOWN             */ "Shift Up",
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ "Brake Pedal",
			/* 13 R2               */ "Gas Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move / Steering Wheel",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// three buttons: Hold / Punch / Kick
	// verified: NOT YET MEASURED IN GAME
	{
		"doa",
		SETS_doa,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON1 Hold */
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON2 Punch */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON3 Kick */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON2 */ "Punch",
			/*  1 Y        BUTTON1 */ "Hold",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Up",
			/*  5 DOWN             */ "Down",
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A        BUTTON3 */ "Kick",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"dynamcop",
		SETS_dynamcop,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON1 Punch */
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON2 Kick */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON3 Jump */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON2 */ "Kick",
			/*  1 Y        BUTTON1 */ "Punch",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Up",
			/*  5 DOWN             */ "Down",
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A        BUTTON3 */ "Jump",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// as rchase2 with a different PORT_MINMAX
	// verified: NOT YET MEASURED IN GAME
	{
		"gunblade",
		SETS_gunblade,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Button 1 */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Button 1",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Stick X",
			/* 17 LSTICK_Y         */ "Stick Y",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"indy500",
		SETS_indy500,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON1 Shift Up */
			RETRO_DEVICE_ID_JOYPAD_L,  /* BUTTON2 Shift Down */
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON3 View 1 (Zoom In) */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON4 View 2 (Zoom Out) */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON3 */ "View 1 (Zoom In)",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON4 */ "View 2 (Zoom Out)",
			/*  9 X                */ nullptr,
			/* 10 L        BUTTON2 */ "Shift Down",
			/* 11 R        BUTTON1 */ "Shift Up",
			/* 12 L2               */ "Brake Pedal",
			/* 13 R2               */ "Gas Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering Wheel",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"manxtt",
		SETS_manxtt,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON1 Shift Up */
			RETRO_DEVICE_ID_JOYPAD_L,  /* BUTTON2 Shift Down */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L        BUTTON2 */ "Shift Down",
			/* 11 R        BUTTON1 */ "Shift Up",
			/* 12 L2               */ "Brake",
			/* 13 R2               */ "Accelerator",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"model2crx",
		SETS_model2crx,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Button 1 */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Button 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Button 3 */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 Button 4 */
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON5 Button 5 */
			RETRO_DEVICE_ID_JOYPAD_L,  /* BUTTON6 Button 6 */
			SOURCE_L2_AXIS,  /* BUTTON7 Button 7 */
			SOURCE_R2_AXIS,  /* BUTTON8 Button 8 */
			RETRO_DEVICE_ID_JOYPAD_R3,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Button 1",
			/*  1 Y        BUTTON3 */ "Button 3",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON2 */ "Button 2",
			/*  9 X        BUTTON4 */ "Button 4",
			/* 10 L        BUTTON6 */ "Button 6",
			/* 11 R        BUTTON5 */ "Button 5",
			/* 12 L2       BUTTON7 */ "Button 7",
			/* 13 R2       BUTTON8 */ "Button 8",
			/* 14 L3               */ "Service Coin",
			/* 15 R3       BUTTON9 */ "Button 9",
			/* 16 LSTICK_X         */ nullptr,
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// bike cabinet: lean on the left stick, throttle and brake on the triggers, two buttons
	// verified: NOT YET MEASURED IN GAME
	{
		"motoraid",
		SETS_motoraid,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Punch */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Kick */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Punch",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON2 */ "Kick",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ "Brake",
			/* 13 R2               */ "Accelerator",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"overrev",
		SETS_overrev,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON1 Shift Up */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Shift Down */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 View 1 */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 View 2 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y        BUTTON3 */ "View 1",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON2 */ "Shift Down",
			/*  9 X        BUTTON4 */ "View 2",
			/* 10 L                */ nullptr,
			/* 11 R        BUTTON1 */ "Shift Up",
			/* 12 L2               */ "Brake Pedal",
			/* 13 R2               */ "Gas Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering Wheel",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// two buttons only
	// verified: NOT YET MEASURED IN GAME
	{
		"pltkids",
		SETS_pltkids,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Button 1 */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Button 1",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Up",
			/*  5 DOWN             */ "Down",
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A        BUTTON2 */ "Button 2",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// Prop Cycle — flying-bicycle cabinet; the pedal axis (AD_STICK_Z) defaults onto the right stick's X axis.
	// verified: NOT YET MEASURED IN GAME
	{
		"propcycl",
		SETS_propcycl,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			SOURCE_NONE,  /* BUTTON1 Button 1 */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ "Cycle Pedal",
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// as ridgerac, with an added View Change button
	// verified: NOT YET MEASURED IN GAME
	{
		"raverace",
		SETS_raverace,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			SOURCE_NONE,  /* BUTTON1 Button 1 */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Clutch Pedal */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 View Change */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y        BUTTON3 */ "Clutch Pedal",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Shift Down",
			/*  5 DOWN             */ "Shift Up",
			/*  6 LEFT             */ "Shift Left",
			/*  7 RIGHT            */ "Shift Right",
			/*  8 A                */ nullptr,
			/*  9 X        BUTTON4 */ "View Change",
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ "Brake Pedal",
			/* 13 R2               */ "Gas Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move / Steering Wheel",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// aim per player on that player's own left stick, one trigger each
	// verified: NOT YET MEASURED IN GAME
	{
		"rchase2",
		SETS_rchase2,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Button 1 */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Button 1",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Stick X",
			/* 17 LSTICK_Y         */ "Stick Y",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// as rchase2 with a wider range and no reverse; no ROMs locally, so the row is unmeasured
	// verified: NOT YET MEASURED IN GAME
	{
		"rchase2a",
		SETS_rchase2a,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Button 1 */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Button 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Button 3 */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 Button 4 */
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON5 Button 5 */
			RETRO_DEVICE_ID_JOYPAD_L,  /* BUTTON6 Button 6 */
			SOURCE_L2_AXIS,  /* BUTTON7 Button 7 */
			SOURCE_R2_AXIS,  /* BUTTON8 Button 8 */
			RETRO_DEVICE_ID_JOYPAD_R3,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Button 1",
			/*  1 Y        BUTTON3 */ "Button 3",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON2 */ "Button 2",
			/*  9 X        BUTTON4 */ "Button 4",
			/* 10 L        BUTTON6 */ "Button 6",
			/* 11 R        BUTTON5 */ "Button 5",
			/* 12 L2       BUTTON7 */ "Button 7",
			/* 13 R2       BUTTON8 */ "Button 8",
			/* 14 L3               */ "Service Coin",
			/* 15 R3       BUTTON9 */ "Button 9",
			/* 16 LSTICK_X         */ nullptr,
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// ridgerac3m (three-monitor version) shares this port set verbatim via PORT_INCLUDE; MACHINE_NOT_WORKING.
	// verified: NOT YET MEASURED IN GAME
	{
		"ridgera",
		SETS_ridgera,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			SOURCE_NONE,  /* BUTTON1 Button 1 */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Clutch Pedal */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y        BUTTON3 */ "Clutch Pedal",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Shift Down",
			/*  5 DOWN             */ "Shift Up",
			/*  6 LEFT             */ "Shift Left",
			/*  7 RIGHT            */ "Shift Right",
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ "Brake Pedal",
			/* 13 R2               */ "Gas Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move / Steering Wheel",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"ridgera2",
		SETS_ridgera2,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			SOURCE_NONE,  /* BUTTON1 Button 1 */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Clutch Pedal */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y        BUTTON3 */ "Clutch Pedal",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Shift Down",
			/*  5 DOWN             */ "Shift Up",
			/*  6 LEFT             */ "Shift Left",
			/*  7 RIGHT            */ "Shift Right",
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ "Brake Pedal",
			/* 13 R2               */ "Gas Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move / Steering Wheel",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// Ridge Racer Full Scale — as ridgerac (MACHINE_NOT_WORKING, no local ROM to dump) plus a cockpit
	// ignition/AT/MT switch trio; read from source, not a live dump.
	// verified: NOT YET MEASURED IN GAME
	{
		"ridgeracf",
		SETS_ridgeracf,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			SOURCE_NONE,  /* BUTTON1 Button 1 */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Clutch Pedal */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 Ignition Key */
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON5 AT Switch */
			RETRO_DEVICE_ID_JOYPAD_L,  /* BUTTON6 MT Switch */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y        BUTTON3 */ "Clutch Pedal",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Shift Down",
			/*  5 DOWN             */ "Shift Up",
			/*  6 LEFT             */ "Shift Left",
			/*  7 RIGHT            */ "Shift Right",
			/*  8 A                */ nullptr,
			/*  9 X        BUTTON4 */ "Ignition Key",
			/* 10 L        BUTTON6 */ "MT Switch",
			/* 11 R        BUTTON5 */ "AT Switch",
			/* 12 L2               */ "Brake Pedal",
			/* 13 R2               */ "Gas Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move / Steering Wheel",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"schamp",
		SETS_schamp,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Punch */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Kick */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Barrier */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Punch",
			/*  1 Y        BUTTON3 */ "Barrier",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Up",
			/*  5 DOWN             */ "Down",
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A        BUTTON2 */ "Kick",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"sgt24h",
		SETS_sgt24h,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON1 Shift Up */
			RETRO_DEVICE_ID_JOYPAD_L,  /* BUTTON2 Shift Down */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 View 1 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y        BUTTON3 */ "View 1",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L        BUTTON2 */ "Shift Down",
			/* 11 R        BUTTON1 */ "Shift Up",
			/* 12 L2               */ "Brake Pedal",
			/* 13 R2               */ "Gas Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering Wheel",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"skisuprg",
		SETS_skisuprg,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Select 1 */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Select 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Select 3 */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 Zoom Out */
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON5 Zoom In */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Select 1",
			/*  1 Y        BUTTON3 */ "Select 3",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Up",
			/*  5 DOWN             */ "Down",
			/*  6 LEFT             */ "Foot Sensor (L)",
			/*  7 RIGHT            */ "Foot Sensor (R)",
			/*  8 A        BUTTON2 */ "Select 2",
			/*  9 X        BUTTON4 */ "Zoom Out",
			/* 10 L                */ nullptr,
			/* 11 R        BUTTON5 */ "Zoom In",
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move / Inclining",
			/* 17 LSTICK_Y         */ "Move / Swing",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"srallyc",
		SETS_srallyc,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON1 GEAR N */
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON2 GEAR 1 */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON3 GEAR 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON4 GEAR 3 */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON5 GEAR 4 */
			RETRO_DEVICE_ID_JOYPAD_L,  /* BUTTON6 VR */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON2 */ "GEAR 1",
			/*  1 Y        BUTTON4 */ "GEAR 3",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON3 */ "GEAR 2",
			/*  9 X        BUTTON5 */ "GEAR 4",
			/* 10 L        BUTTON6 */ "VR",
			/* 11 R        BUTTON1 */ "Hand Brake / GEAR N",
			/* 12 L2               */ "Brake Pedal",
			/* 13 R2               */ "Accelerate Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering Wheel",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// Star Blade — analog aim on the left stick, fire on B.
	// verified: NOT YET MEASURED IN GAME
	{
		"starblad",
		SETS_starblad,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Fire */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Button 2 */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Button 3 */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 (unused) */
			SOURCE_NONE,  /* BUTTON6 (unused) */
			SOURCE_NONE,  /* BUTTON7 (unused) */
			SOURCE_NONE,  /* BUTTON8 (unused) */
			SOURCE_NONE,  /* BUTTON9 (unused) */
		},
		{
			/*  0 B        BUTTON1 */ "Fire",
			/*  1 Y        BUTTON3 */ "Button 3",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON2 */ "Button 2",
			/*  9 X        BUTTON4 */ "Button 4",
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Aim",
			/* 17 LSTICK_Y         */ "Aim",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// lightgun cabinet, same shape as vcop; Foot Pedal is Time Crisis's cover/reload pedal, put on A for a pad
	// player
	// verified: NOT YET MEASURED IN GAME
	{
		"timecris",
		SETS_timecris,
		true,
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Gun Trigger */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Foot Pedal */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Gun Trigger",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A        BUTTON2 */ "Foot Pedal",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Aim X",
			/* 17 LSTICK_Y         */ "Aim Y",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// Tokyo Wars — tank sim: wheel + two pedals (forward/backward) + twin cannon triggers; not a lightgun cabinet
	// despite the name.
	// verified: NOT YET MEASURED IN GAME
	{
		"tokyowar",
		SETS_tokyowar,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			SOURCE_NONE,  /* BUTTON1 Button 1 */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 Left Trigger */
			RETRO_DEVICE_ID_JOYPAD_R,  /* BUTTON5 Right Trigger */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X        BUTTON4 */ "Left Trigger",
			/* 10 L                */ nullptr,
			/* 11 R        BUTTON5 */ "Right Trigger",
			/* 12 L2               */ "Backward Pedal",
			/* 13 R2               */ "Forward Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move / Steering Wheel",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// lightgun cabinet; on a port left as a pad the trigger is button 1 and aim is the left stick
	// verified: NOT YET MEASURED IN GAME
	{
		"vcop",
		SETS_vcop,
		true,
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Trigger */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Trigger",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Aim X",
			/* 17 LSTICK_Y         */ "Aim Y",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// lightgun cabinet, same shape as vcop
	// verified: NOT YET MEASURED IN GAME
	{
		"vcop2",
		SETS_vcop2,
		true,
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Trigger */
			SOURCE_NONE,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Trigger",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ nullptr,
			/*  5 DOWN             */ nullptr,
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Aim X",
			/* 17 LSTICK_Y         */ "Aim Y",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// three-button fighter on a four-way stick; shared by fvipers, lastbrnx and hpyagu98
	// verified: NOT YET MEASURED IN GAME
	{
		"vf2",
		SETS_vf2,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Punch */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Kick */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Guard */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Punch",
			/*  1 Y        BUTTON3 */ "Guard",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Up",
			/*  5 DOWN             */ "Down",
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A        BUTTON2 */ "Kick",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// verified: NOT YET MEASURED IN GAME
	{
		"victlap",
		SETS_victlap,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			SOURCE_NONE,  /* BUTTON1 Dev Service Enter */
			SOURCE_NONE,  /* BUTTON2 Dev Service Exit */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 View Change */
			RETRO_DEVICE_ID_JOYPAD_X,  /* BUTTON4 Motion-Stop */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y        BUTTON3 */ "View Change",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Dev Service Up",
			/*  5 DOWN             */ "Dev Service Down",
			/*  6 LEFT             */ "Dev Service Left",
			/*  7 RIGHT            */ "Dev Service Right",
			/*  8 A                */ nullptr,
			/*  9 X        BUTTON4 */ "Motion-Stop",
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ "Brake Pedal",
			/* 13 R2               */ "Gas Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move / Steering Wheel",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// three buttons. The driver's bit order is not its button order; these are by button number
	// verified: NOT YET MEASURED IN GAME
	{
		"vstriker",
		SETS_vstriker,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Short Pass */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Long Pass */
			RETRO_DEVICE_ID_JOYPAD_Y,  /* BUTTON3 Shoot */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Short Pass",
			/*  1 Y        BUTTON3 */ "Shoot",
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Up",
			/*  5 DOWN             */ "Down",
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A        BUTTON2 */ "Long Pass",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// Winning Run — wheel, gas/brake pedals, up/down gearshift on the d-pad.
	// verified: NOT YET MEASURED IN GAME
	{
		"winrun",
		SETS_winrun,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			SOURCE_NONE,  /* BUTTON1 (unused) */
			SOURCE_NONE,  /* BUTTON2 (unused) */
			SOURCE_NONE,  /* BUTTON3 (unused) */
			SOURCE_NONE,  /* BUTTON4 (unused) */
			SOURCE_NONE,  /* BUTTON5 (unused) */
			SOURCE_NONE,  /* BUTTON6 (unused) */
			SOURCE_NONE,  /* BUTTON7 (unused) */
			SOURCE_NONE,  /* BUTTON8 (unused) */
			SOURCE_NONE,  /* BUTTON9 (unused) */
		},
		{
			/*  0 B                */ nullptr,
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Shift Down",
			/*  5 DOWN             */ "Shift Up",
			/*  6 LEFT             */ nullptr,
			/*  7 RIGHT            */ nullptr,
			/*  8 A                */ nullptr,
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ "Brake Pedal",
			/* 13 R2               */ "Gas Pedal",
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Steering Wheel",
			/* 17 LSTICK_Y         */ nullptr,
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	},
	// two buttons only
	// verified: NOT YET MEASURED IN GAME
	{
		"zerogun",
		SETS_zerogun,
		false,   // no IPT_LIGHTGUN_X/Y: send no gun descriptors
		false,  // not a single-pad twin-stick cabinet
		{
			RETRO_DEVICE_ID_JOYPAD_B,  /* BUTTON1 Button 1 */
			RETRO_DEVICE_ID_JOYPAD_A,  /* BUTTON2 Button 2 */
			SOURCE_NONE,  /* BUTTON3 Button 3 */
			SOURCE_NONE,  /* BUTTON4 Button 4 */
			SOURCE_NONE,  /* BUTTON5 Button 5 */
			SOURCE_NONE,  /* BUTTON6 Button 6 */
			SOURCE_NONE,  /* BUTTON7 Button 7 */
			SOURCE_NONE,  /* BUTTON8 Button 8 */
			SOURCE_NONE,  /* BUTTON9 Button 9 */
		},
		{
			/*  0 B        BUTTON1 */ "Button 1",
			/*  1 Y                */ nullptr,
			/*  2 SELECT           */ "Coin",
			/*  3 START            */ "Start",
			/*  4 UP               */ "Up",
			/*  5 DOWN             */ "Down",
			/*  6 LEFT             */ "Left",
			/*  7 RIGHT            */ "Right",
			/*  8 A        BUTTON2 */ "Button 2",
			/*  9 X                */ nullptr,
			/* 10 L                */ nullptr,
			/* 11 R                */ nullptr,
			/* 12 L2               */ nullptr,
			/* 13 R2               */ nullptr,
			/* 14 L3               */ "Service Coin",
			/* 15 R3               */ nullptr,
			/* 16 LSTICK_X         */ "Move",
			/* 17 LSTICK_Y         */ "Move",
			/* 18 RSTICK_X         */ nullptr,
			/* 19 RSTICK_Y         */ nullptr,
		},
	}
};

static_assert(std::size(GAME_LAYOUTS) == 43, "regenerate input_layouts.ipp");
